
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CETAP_LOB.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Barcode
{

    public int Id { get; set; }

    public long BarcodeNo { get; set; }

    public bool OnlineTest { get; set; }

    public string LastNumber { get; set; }

    public int Year { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime DateCreated { get; set; }

    public string ModifiedBy { get; set; }

    public System.DateTime DateModified { get; set; }

}

}
