//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CETAP_LOB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cleaned_batch
    {
        public long rec_id { get; set; }
        public int CSX_type_id { get; set; }
        public string CSX { get; set; }
        public long Barcode { get; set; }
        public long NBT { get; set; }
        public Nullable<long> SAID { get; set; }
        public string ForeignID { get; set; }
        public Nullable<int> IDType { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Citizenship { get; set; }
        public string Faculty { get; set; }
        public System.DateTime DOB { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Initials { get; set; }
        public Nullable<int> VenueCode { get; set; }
        public System.DateTime DOT { get; set; }
        public Nullable<int> HomeLanguage { get; set; }
        public Nullable<int> SchoolLanguage { get; set; }
        public Nullable<int> Classification { get; set; }
        public string AQL_language { get; set; }
        public Nullable<int> AQL_code { get; set; }
        public string AQL_section1 { get; set; }
        public string AQL_section2 { get; set; }
        public string AQL_section3 { get; set; }
        public string AQL_section4 { get; set; }
        public string AQL_section5 { get; set; }
        public string AQL_section6 { get; set; }
        public string AQL_section7 { get; set; }
        public string Maths_Language { get; set; }
        public Nullable<int> Math_code { get; set; }
        public string Math_section { get; set; }
        public string Faculty1 { get; set; }
        public string Faculty2 { get; set; }
        public string Faculty3 { get; set; }
        public int BatchID { get; set; }
        public string created_by { get; set; }
        public System.DateTime date_created { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    }
}
