
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CETAP_LOB.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Domain
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string description { get; set; }

    public string created_by { get; set; }

    public Nullable<System.DateTime> date_created { get; set; }

    public string modified_by { get; set; }

    public Nullable<System.DateTime> date_modified { get; set; }

}

}
