//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CETAP_LOB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EasyPayRecord
    {
        public long PayNumber { get; set; }
        public int FileGenerationNumber { get; set; }
        public long PayTag { get; set; }
        public Nullable<long> CollectorID { get; set; }
        public string date { get; set; }
        public string Time { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public Nullable<decimal> BankCost { get; set; }
        public short NumOfTrans { get; set; }
        public decimal AmountPaid { get; set; }
        public string Trace { get; set; }
        public string TenderType_PAN { get; set; }
        public string PointOfService { get; set; }
        public short Original { get; set; }
    
        public virtual EasyPayFile EasyPayFile { get; set; }
        public virtual WritersPayment WritersPayment { get; set; }
    }
}
