//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CETAP_LOB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntakeYear
    {
        public int yearID { get; set; }
        public int Year { get; set; }
        public System.DateTime yearStart { get; set; }
        public System.DateTime yearEnd { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
