
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CETAP_LOB.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Itembank
{

    public int Id { get; set; }

    public string ItemName { get; set; }

    public string ItemKey { get; set; }

    public Nullable<int> NoOfKeys { get; set; }

    public bool MultipleChoice { get; set; }

    public Nullable<int> Cognitive_level { get; set; }

    public Nullable<int> Difficulty_level { get; set; }

    public Nullable<bool> Operational { get; set; }

    public Nullable<int> Subdomain_id { get; set; }

    public string Primary_cluster { get; set; }

    public string Secondary_cluster { get; set; }

    public double Discriminating { get; set; }

    public double Difficulty { get; set; }

    public double Guessing { get; set; }

    public string Description { get; set; }

    public string created_by { get; set; }

    public Nullable<System.DateTime> date_created { get; set; }

    public string modified_by { get; set; }

    public Nullable<System.DateTime> date_modified { get; set; }

}

}
