
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CETAP_LOB.Database
{

using System;
    using System.Collections.Generic;
    
public partial class LogisticsComposit
{

    public Nullable<long> Test_Session_ID { get; set; }

    public long NBT_Reference { get; set; }

    public string Registered_Walk_in { get; set; }

    public string Surname { get; set; }

    public string First_Name { get; set; }

    public string Middle_Initials { get; set; }

    public Nullable<long> South_African_ID { get; set; }

    public string Foreign_ID { get; set; }

    public string Date_of_Birth { get; set; }

    public string WroteAL { get; set; }

    public string WroteQL { get; set; }

    public string WroteMat { get; set; }

    public string Student_Number { get; set; }

    public string Faculty { get; set; }

    public string Programme { get; set; }

    public string Date_of_Test { get; set; }

    public string VenueName { get; set; }

    public string Province_Region { get; set; }

    public string Gender { get; set; }

    public Nullable<int> AL_Score { get; set; }

    public string AL_Performance { get; set; }

    public Nullable<int> QLScore { get; set; }

    public string QL_Performance { get; set; }

    public Nullable<int> MATScore { get; set; }

    public string Maths_Performance { get; set; }

    public string AQL_TEST_LANGUAGE { get; set; }

    public string MATHS_TEST_LANGUAGE { get; set; }

    public string EasyPay_Payment { get; set; }

    public string Bank_Payment { get; set; }

    public string AmountPaid { get; set; }

    public string Client { get; set; }

}

}
