//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CETAP_LOB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewNBTNumber
    {
        public long NewNBT { get; set; }
        public Nullable<long> OriginalNBT { get; set; }
        public bool Used { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<int> WriterListID { get; set; }
    }
}
