//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CETAP_LOB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanTracker
    {
        public int Id { get; set; }
        public string BatchedBy { get; set; }
        public Nullable<System.DateTime> DateBatched { get; set; }
        public Nullable<int> Records { get; set; }
        public Nullable<System.DateTime> DateScanned { get; set; }
        public Nullable<int> ScanRecords { get; set; }
        public Nullable<System.DateTime> DateEdited { get; set; }
        public Nullable<int> EditRecords { get; set; }
        public Nullable<System.DateTime> DateQA { get; set; }
        public Nullable<int> QARecords { get; set; }
        public Nullable<System.DateTime> DateSentForScoring { get; set; }
        public Nullable<int> SentCount { get; set; }
        public Nullable<System.DateTime> DateScored { get; set; }
        public Nullable<int> ScoredRecords { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
