//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CETAP_LOB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScannedFile
    {
        public int FileID { get; set; }
        public string Filename { get; set; }
        public System.DateTime Datescanned { get; set; }
        public byte[] FileData { get; set; }
        public Nullable<int> BatchID { get; set; }
        public System.DateTime DateModified { get; set; }
        public byte[] RowVersion { get; set; }
        public string Client { get; set; }
    
        public virtual Batch Batch { get; set; }
    }
}
