
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CETAP_LOB.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Subdomain
{

    public int Id { get; set; }

    public string Name { get; set; }

    public int Domain_id { get; set; }

    public string Description { get; set; }

    public System.DateTime date_created { get; set; }

    public System.DateTime date_modified { get; set; }

}

}
