//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CETAP_LOB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_EasyPayRecords
    {
        public int File_Number { get; set; }
        public long NBT_Ref { get; set; }
        public Nullable<long> EasyPay_Code { get; set; }
        public string Source_File_Date { get; set; }
        public string Payment_Date { get; set; }
        public decimal Fee { get; set; }
        public Nullable<decimal> Processing_Fee { get; set; }
        public Nullable<decimal> Transaction_Fee { get; set; }
        public string Paid_Amount { get; set; }
        public long Pay_Code { get; set; }
        public string Payee_Name { get; set; }
        public string Payment_Method { get; set; }
        public string Bank_Reference { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<decimal> Expenses { get; set; }
        public Nullable<decimal> Net { get; set; }
    }
}
